### ISSUE TITLE
Clear Cart

### ISSUE THREAD

**Issue by premkumarkori** [edocbuhtig/ionic-angular-shopping-cart-stripe#4]
I have seen the code but after checkout. How to clear the cart?

**Comment by edocbuhtig** [comment]
@premkumarkori Please explain your concern or issue in detail with some code samples, one liner will not help us both, what are you trying to achieve, it is hard to understand.

**Comment by premkumarkori** [comment]
I was trying to built same application using firebase. I find this code similar, In the cart service the cart array which is an observable array is not getting clear after the pay option. How to clear the observable array? How to assign it to localstorage and clear it.
